export type InstrumentKey = "guitar" | "synth" | "bass" | "drums";

type DrumName = "kick" | "snare" | "hat";

export type SequenceEvent =
  | {
      type: "melodic";
      time: string;
      notes: string[];
      duration: string;
      velocity?: number;
    }
  | {
      type: "drum";
      time: string;
      drum: DrumName;
      duration?: string;
      velocity?: number;
    };

export interface InstrumentSequence {
  id: string;
  name: string;
  events: SequenceEvent[];
}

export interface InstrumentDefinition {
  key: InstrumentKey;
  displayName: string;
  sequences: InstrumentSequence[];
}

export const LOOP_LENGTH = "4m";
export const BPM = 92;

export const INSTRUMENTS: InstrumentDefinition[] = [
  {
    key: "guitar",
    displayName: "Гитара",
    sequences: [
      {
        id: "gtr-rain-strum",
        name: "Rain Strum",
        events: [
          {
            type: "melodic",
            time: "0:0",
            notes: ["D4", "F4", "A4"],
            duration: "2n",
            velocity: 0.8,
          },
          {
            type: "melodic",
            time: "0:2",
            notes: ["Bb3", "D4", "F4"],
            duration: "2n",
            velocity: 0.7,
          },
          {
            type: "melodic",
            time: "1:0",
            notes: ["C4", "E4", "G4"],
            duration: "2n",
            velocity: 0.8,
          },
          {
            type: "melodic",
            time: "1:2",
            notes: ["A3", "C4", "E4"],
            duration: "2n",
            velocity: 0.75,
          },
          {
            type: "melodic",
            time: "2:0",
            notes: ["D4", "F4", "A4"],
            duration: "1m",
            velocity: 0.85,
          },
          {
            type: "melodic",
            time: "3:0",
            notes: ["C4", "E4", "G4"],
            duration: "1m",
            velocity: 0.8,
          },
        ],
      },
      {
        id: "gtr-muted-echo",
        name: "Muted Echo",
        events: [
          { type: "melodic", time: "0:0", notes: ["D4"], duration: "8n", velocity: 0.75 },
          { type: "melodic", time: "0:1", notes: ["F4"], duration: "8n", velocity: 0.7 },
          { type: "melodic", time: "0:2", notes: ["A4"], duration: "8n", velocity: 0.72 },
          { type: "melodic", time: "0:3", notes: ["C5"], duration: "8n", velocity: 0.68 },
          { type: "melodic", time: "1:0", notes: ["F4"], duration: "8n", velocity: 0.72 },
          { type: "melodic", time: "1:1", notes: ["A4"], duration: "8n", velocity: 0.7 },
          { type: "melodic", time: "1:2", notes: ["C5"], duration: "8n", velocity: 0.68 },
          { type: "melodic", time: "1:3", notes: ["D5"], duration: "8n", velocity: 0.66 },
          { type: "melodic", time: "2:0", notes: ["E4"], duration: "8n", velocity: 0.74 },
          { type: "melodic", time: "2:1", notes: ["G4"], duration: "8n", velocity: 0.7 },
          { type: "melodic", time: "2:2", notes: ["Bb4"], duration: "8n", velocity: 0.72 },
          { type: "melodic", time: "2:3", notes: ["C5"], duration: "8n", velocity: 0.68 },
          { type: "melodic", time: "3:0", notes: ["A4"], duration: "8n", velocity: 0.74 },
          { type: "melodic", time: "3:1", notes: ["C5"], duration: "8n", velocity: 0.7 },
          { type: "melodic", time: "3:2", notes: ["D5"], duration: "8n", velocity: 0.68 },
          { type: "melodic", time: "3:3", notes: ["F5"], duration: "8n", velocity: 0.66 },
        ],
      },
      {
        id: "gtr-cold-harmony",
        name: "Cold Harmony",
        events: [
          { type: "melodic", time: "0:0", notes: ["D4", "A4"], duration: "1m", velocity: 0.78 },
          { type: "melodic", time: "1:0", notes: ["F4", "C5"], duration: "1m", velocity: 0.76 },
          { type: "melodic", time: "2:0", notes: ["G4", "D5"], duration: "1m", velocity: 0.74 },
          { type: "melodic", time: "3:0", notes: ["A4", "E5"], duration: "1m", velocity: 0.72 },
          { type: "melodic", time: "3:2", notes: ["Bb4", "F5"], duration: "2n", velocity: 0.68 },
        ],
      },
      {
        id: "gtr-rise",
        name: "Rise",
        events: [
          { type: "melodic", time: "0:0", notes: ["D4"], duration: "4n", velocity: 0.75 },
          { type: "melodic", time: "0:2", notes: ["F4"], duration: "4n", velocity: 0.72 },
          { type: "melodic", time: "1:0", notes: ["A4"], duration: "4n", velocity: 0.74 },
          { type: "melodic", time: "1:2", notes: ["C5"], duration: "4n", velocity: 0.7 },
          { type: "melodic", time: "2:0", notes: ["Bb4"], duration: "4n", velocity: 0.72 },
          { type: "melodic", time: "2:2", notes: ["A4"], duration: "4n", velocity: 0.72 },
          { type: "melodic", time: "3:0", notes: ["G4"], duration: "4n", velocity: 0.7 },
          { type: "melodic", time: "3:2", notes: ["F4"], duration: "4n", velocity: 0.7 },
        ],
      },
    ],
  },
  {
    key: "synth",
    displayName: "Синт",
    sequences: [
      {
        id: "synth-midnight-chords",
        name: "Midnight Chords",
        events: [
          { type: "melodic", time: "0:0", notes: ["D5", "A5"], duration: "1m", velocity: 0.42 },
          { type: "melodic", time: "1:0", notes: ["F4", "C5", "A5"], duration: "1m", velocity: 0.4 },
          { type: "melodic", time: "2:0", notes: ["G4", "D5", "Bb5"], duration: "1m", velocity: 0.38 },
          { type: "melodic", time: "3:0", notes: ["A4", "E5", "C6"], duration: "1m", velocity: 0.4 },
        ],
      },
      {
        id: "synth-echo-pulse",
        name: "Echo Pulse",
        events: [
          { type: "melodic", time: "0:0", notes: ["A5"], duration: "4n", velocity: 0.5 },
          { type: "melodic", time: "0:1:2", notes: ["D6"], duration: "8n", velocity: 0.46 },
          { type: "melodic", time: "0:3", notes: ["F6"], duration: "8n", velocity: 0.44 },
          { type: "melodic", time: "1:0", notes: ["E6"], duration: "4n", velocity: 0.46 },
          { type: "melodic", time: "1:2", notes: ["C6"], duration: "8n", velocity: 0.44 },
          { type: "melodic", time: "1:3:2", notes: ["A5"], duration: "8n", velocity: 0.42 },
          { type: "melodic", time: "2:1", notes: ["Bb5"], duration: "4n", velocity: 0.44 },
          { type: "melodic", time: "2:2:2", notes: ["G5"], duration: "8n", velocity: 0.42 },
          { type: "melodic", time: "2:3:2", notes: ["E5"], duration: "8n", velocity: 0.4 },
          { type: "melodic", time: "3:1", notes: ["C6"], duration: "4n", velocity: 0.42 },
          { type: "melodic", time: "3:2:2", notes: ["A5"], duration: "8n", velocity: 0.4 },
        ],
      },
      {
        id: "synth-frozen-air",
        name: "Frozen Air",
        events: [
          { type: "melodic", time: "0:0", notes: ["D5", "F5", "A5"], duration: "2n", velocity: 0.38 },
          { type: "melodic", time: "0:2", notes: ["C5", "E5", "G5"], duration: "2n", velocity: 0.36 },
          { type: "melodic", time: "1:0", notes: ["Bb4", "D5", "G5"], duration: "2n", velocity: 0.34 },
          { type: "melodic", time: "1:2", notes: ["A4", "C5", "F5"], duration: "2n", velocity: 0.36 },
          { type: "melodic", time: "2:0", notes: ["D5", "F5", "A5"], duration: "2n", velocity: 0.38 },
          { type: "melodic", time: "2:2", notes: ["F5", "A5", "C6"], duration: "2n", velocity: 0.36 },
          { type: "melodic", time: "3:0", notes: ["E5", "G5", "C6"], duration: "2n", velocity: 0.34 },
          { type: "melodic", time: "3:2", notes: ["D5", "F5", "Bb5"], duration: "2n", velocity: 0.36 },
        ],
      },
      {
        id: "synth-shiver",
        name: "Shiver",
        events: [
          { type: "melodic", time: "0:0", notes: ["D6"], duration: "16n", velocity: 0.58 },
          { type: "melodic", time: "0:0:2", notes: ["F6"], duration: "16n", velocity: 0.55 },
          { type: "melodic", time: "0:1", notes: ["A5"], duration: "16n", velocity: 0.52 },
          { type: "melodic", time: "0:1:2", notes: ["C6"], duration: "16n", velocity: 0.5 },
          { type: "melodic", time: "0:2", notes: ["D6"], duration: "16n", velocity: 0.5 },
          { type: "melodic", time: "0:2:2", notes: ["F6"], duration: "16n", velocity: 0.48 },
          { type: "melodic", time: "0:3", notes: ["A5"], duration: "16n", velocity: 0.48 },
          { type: "melodic", time: "0:3:2", notes: ["C6"], duration: "16n", velocity: 0.46 },
          { type: "melodic", time: "1:0", notes: ["E6"], duration: "16n", velocity: 0.5 },
          { type: "melodic", time: "1:0:2", notes: ["G6"], duration: "16n", velocity: 0.48 },
          { type: "melodic", time: "1:1", notes: ["Bb5"], duration: "16n", velocity: 0.46 },
          { type: "melodic", time: "1:1:2", notes: ["C6"], duration: "16n", velocity: 0.44 },
          { type: "melodic", time: "1:2", notes: ["D6"], duration: "16n", velocity: 0.46 },
          { type: "melodic", time: "1:2:2", notes: ["F6"], duration: "16n", velocity: 0.44 },
          { type: "melodic", time: "1:3", notes: ["A5"], duration: "16n", velocity: 0.42 },
          { type: "melodic", time: "1:3:2", notes: ["C6"], duration: "16n", velocity: 0.4 },
          { type: "melodic", time: "2:0", notes: ["F5"], duration: "16n", velocity: 0.46 },
          { type: "melodic", time: "2:1", notes: ["A5"], duration: "16n", velocity: 0.42 },
          { type: "melodic", time: "2:2", notes: ["D6"], duration: "16n", velocity: 0.44 },
          { type: "melodic", time: "2:3", notes: ["C6"], duration: "16n", velocity: 0.42 },
          { type: "melodic", time: "3:0", notes: ["Bb5"], duration: "16n", velocity: 0.44 },
          { type: "melodic", time: "3:1", notes: ["A5"], duration: "16n", velocity: 0.42 },
          { type: "melodic", time: "3:2", notes: ["G5"], duration: "16n", velocity: 0.4 },
          { type: "melodic", time: "3:3", notes: ["F5"], duration: "16n", velocity: 0.38 },
        ],
      },
    ],
  },
  {
    key: "bass",
    displayName: "Басс",
    sequences: [
      {
        id: "bass-foundation",
        name: "Foundation",
        events: [
          { type: "melodic", time: "0:0", notes: ["D2"], duration: "2n", velocity: 0.8 },
          { type: "melodic", time: "0:2", notes: ["C2"], duration: "2n", velocity: 0.78 },
          { type: "melodic", time: "1:0", notes: ["Bb1"], duration: "2n", velocity: 0.76 },
          { type: "melodic", time: "1:2", notes: ["A1"], duration: "2n", velocity: 0.74 },
          { type: "melodic", time: "2:0", notes: ["D2"], duration: "2n", velocity: 0.78 },
          { type: "melodic", time: "2:2", notes: ["F2"], duration: "2n", velocity: 0.76 },
          { type: "melodic", time: "3:0", notes: ["A1"], duration: "2n", velocity: 0.74 },
          { type: "melodic", time: "3:2", notes: ["C2"], duration: "2n", velocity: 0.72 },
        ],
      },
      {
        id: "bass-steps",
        name: "Steps",
        events: [
          { type: "melodic", time: "0:0", notes: ["D2"], duration: "4n", velocity: 0.84 },
          { type: "melodic", time: "0:1", notes: ["D3"], duration: "4n", velocity: 0.8 },
          { type: "melodic", time: "0:2", notes: ["C2"], duration: "4n", velocity: 0.82 },
          { type: "melodic", time: "0:3", notes: ["C3"], duration: "4n", velocity: 0.78 },
          { type: "melodic", time: "1:0", notes: ["Bb1"], duration: "4n", velocity: 0.8 },
          { type: "melodic", time: "1:1", notes: ["Bb2"], duration: "4n", velocity: 0.78 },
          { type: "melodic", time: "1:2", notes: ["A1"], duration: "4n", velocity: 0.76 },
          { type: "melodic", time: "1:3", notes: ["A2"], duration: "4n", velocity: 0.74 },
          { type: "melodic", time: "2:0", notes: ["D2"], duration: "4n", velocity: 0.8 },
          { type: "melodic", time: "2:1", notes: ["F2"], duration: "4n", velocity: 0.78 },
          { type: "melodic", time: "2:2", notes: ["E2"], duration: "4n", velocity: 0.76 },
          { type: "melodic", time: "2:3", notes: ["F2"], duration: "4n", velocity: 0.74 },
          { type: "melodic", time: "3:0", notes: ["A1"], duration: "4n", velocity: 0.76 },
          { type: "melodic", time: "3:1", notes: ["C2"], duration: "4n", velocity: 0.74 },
          { type: "melodic", time: "3:2", notes: ["D2"], duration: "4n", velocity: 0.72 },
          { type: "melodic", time: "3:3", notes: ["C2"], duration: "4n", velocity: 0.7 },
        ],
      },
      {
        id: "bass-syncopate",
        name: "Syncopate",
        events: [
          { type: "melodic", time: "0:0", notes: ["D2"], duration: "8n", velocity: 0.82 },
          { type: "melodic", time: "0:1:2", notes: ["C2"], duration: "8n", velocity: 0.8 },
          { type: "melodic", time: "0:3", notes: ["F2"], duration: "8n", velocity: 0.78 },
          { type: "melodic", time: "1:0:2", notes: ["A1"], duration: "8n", velocity: 0.76 },
          { type: "melodic", time: "1:2", notes: ["Bb1"], duration: "8n", velocity: 0.76 },
          { type: "melodic", time: "1:3:2", notes: ["C2"], duration: "8n", velocity: 0.74 },
          { type: "melodic", time: "2:1", notes: ["D2"], duration: "8n", velocity: 0.76 },
          { type: "melodic", time: "2:2:2", notes: ["F2"], duration: "8n", velocity: 0.74 },
          { type: "melodic", time: "2:3:2", notes: ["A1"], duration: "8n", velocity: 0.72 },
          { type: "melodic", time: "3:1", notes: ["C2"], duration: "8n", velocity: 0.72 },
          { type: "melodic", time: "3:2:2", notes: ["D2"], duration: "8n", velocity: 0.7 },
        ],
      },
      {
        id: "bass-surge",
        name: "Surge",
        events: [
          { type: "melodic", time: "0:0", notes: ["D2"], duration: "1m", velocity: 0.82 },
          { type: "melodic", time: "1:0", notes: ["F2"], duration: "1m", velocity: 0.8 },
          { type: "melodic", time: "2:0", notes: ["G1"], duration: "1m", velocity: 0.78 },
          { type: "melodic", time: "3:0", notes: ["A1"], duration: "1m", velocity: 0.76 },
        ],
      },
    ],
  },
  {
    key: "drums",
    displayName: "Ударные",
    sequences: [
      {
        id: "drums-pulse",
        name: "Pulse",
        events: [
          { type: "drum", time: "0:0", drum: "kick", velocity: 0.9 },
          { type: "drum", time: "0:2", drum: "kick", velocity: 0.85 },
          { type: "drum", time: "1:0", drum: "kick", velocity: 0.88 },
          { type: "drum", time: "1:2", drum: "snare", velocity: 0.8 },
          { type: "drum", time: "2:0", drum: "kick", velocity: 0.86 },
          { type: "drum", time: "2:2", drum: "kick", velocity: 0.84 },
          { type: "drum", time: "3:0", drum: "kick", velocity: 0.88 },
          { type: "drum", time: "3:2", drum: "snare", velocity: 0.82 },
          { type: "drum", time: "0:0", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "0:1", drum: "hat", velocity: 0.42 },
          { type: "drum", time: "0:2", drum: "hat", velocity: 0.44 },
          { type: "drum", time: "0:3", drum: "hat", velocity: 0.42 },
          { type: "drum", time: "1:0", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "1:1", drum: "hat", velocity: 0.42 },
          { type: "drum", time: "1:2", drum: "hat", velocity: 0.44 },
          { type: "drum", time: "1:3", drum: "hat", velocity: 0.42 },
          { type: "drum", time: "2:0", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "2:1", drum: "hat", velocity: 0.42 },
          { type: "drum", time: "2:2", drum: "hat", velocity: 0.44 },
          { type: "drum", time: "2:3", drum: "hat", velocity: 0.42 },
          { type: "drum", time: "3:0", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "3:1", drum: "hat", velocity: 0.42 },
          { type: "drum", time: "3:2", drum: "hat", velocity: 0.44 },
          { type: "drum", time: "3:3", drum: "hat", velocity: 0.42 },
        ],
      },
      {
        id: "drums-half-time",
        name: "Half-Time",
        events: [
          { type: "drum", time: "0:0", drum: "kick", velocity: 0.92 },
          { type: "drum", time: "1:2", drum: "snare", velocity: 0.85 },
          { type: "drum", time: "3:2", drum: "snare", velocity: 0.86 },
          { type: "drum", time: "2:0", drum: "kick", velocity: 0.88 },
          { type: "drum", time: "0:0", drum: "hat", velocity: 0.32 },
          { type: "drum", time: "0:1:2", drum: "hat", velocity: 0.35 },
          { type: "drum", time: "0:3", drum: "hat", velocity: 0.32 },
          { type: "drum", time: "1:0:2", drum: "hat", velocity: 0.34 },
          { type: "drum", time: "1:1:2", drum: "hat", velocity: 0.33 },
          { type: "drum", time: "1:3", drum: "hat", velocity: 0.34 },
          { type: "drum", time: "2:0:2", drum: "hat", velocity: 0.33 },
          { type: "drum", time: "2:1:2", drum: "hat", velocity: 0.32 },
          { type: "drum", time: "2:3", drum: "hat", velocity: 0.33 },
          { type: "drum", time: "3:0:2", drum: "hat", velocity: 0.32 },
          { type: "drum", time: "3:1:2", drum: "hat", velocity: 0.33 },
          { type: "drum", time: "3:3", drum: "hat", velocity: 0.34 },
        ],
      },
      {
        id: "drums-gallop",
        name: "Gallop",
        events: [
          { type: "drum", time: "0:0", drum: "kick", velocity: 0.9 },
          { type: "drum", time: "0:0:3", drum: "kick", velocity: 0.86 },
          { type: "drum", time: "0:1:2", drum: "kick", velocity: 0.84 },
          { type: "drum", time: "0:2:2", drum: "kick", velocity: 0.84 },
          { type: "drum", time: "1:0", drum: "snare", velocity: 0.82 },
          { type: "drum", time: "1:2", drum: "snare", velocity: 0.84 },
          { type: "drum", time: "2:0", drum: "kick", velocity: 0.88 },
          { type: "drum", time: "2:0:3", drum: "kick", velocity: 0.84 },
          { type: "drum", time: "2:1:2", drum: "kick", velocity: 0.82 },
          { type: "drum", time: "2:2:2", drum: "kick", velocity: 0.82 },
          { type: "drum", time: "3:0", drum: "snare", velocity: 0.82 },
          { type: "drum", time: "3:2", drum: "snare", velocity: 0.84 },
          { type: "drum", time: "0:0", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "0:0:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "0:1", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "0:1:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "0:2", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "0:2:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "0:3", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "0:3:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "1:0", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "1:0:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "1:1", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "1:1:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "1:2", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "1:2:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "1:3", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "1:3:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "2:0", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "2:0:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "2:1", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "2:1:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "2:2", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "2:2:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "2:3", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "2:3:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "3:0", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "3:0:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "3:1", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "3:1:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "3:2", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "3:2:2", drum: "hat", velocity: 0.43 },
          { type: "drum", time: "3:3", drum: "hat", velocity: 0.45 },
          { type: "drum", time: "3:3:2", drum: "hat", velocity: 0.43 },
        ],
      },
      {
        id: "drums-stutter",
        name: "Stutter",
        events: [
          { type: "drum", time: "0:0", drum: "kick", velocity: 0.88 },
          { type: "drum", time: "0:1:2", drum: "kick", velocity: 0.84 },
          { type: "drum", time: "0:2:2", drum: "kick", velocity: 0.82 },
          { type: "drum", time: "1:0", drum: "snare", velocity: 0.84 },
          { type: "drum", time: "1:1:3", drum: "kick", velocity: 0.82 },
          { type: "drum", time: "1:2:2", drum: "snare", velocity: 0.86 },
          { type: "drum", time: "2:0", drum: "kick", velocity: 0.88 },
          { type: "drum", time: "2:1:2", drum: "kick", velocity: 0.84 },
          { type: "drum", time: "2:2:2", drum: "kick", velocity: 0.82 },
          { type: "drum", time: "3:0", drum: "snare", velocity: 0.84 },
          { type: "drum", time: "3:1:3", drum: "kick", velocity: 0.82 },
          { type: "drum", time: "3:2:2", drum: "snare", velocity: 0.86 },
          { type: "drum", time: "0:0", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "0:0:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "0:1", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "0:1:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "0:2", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "0:2:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "0:3", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "0:3:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "1:0", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "1:0:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "1:1", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "1:1:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "1:2", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "1:2:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "1:3", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "1:3:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "2:0", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "2:0:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "2:1", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "2:1:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "2:2", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "2:2:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "2:3", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "2:3:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "3:0", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "3:0:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "3:1", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "3:1:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "3:2", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "3:2:2", drum: "hat", velocity: 0.4 },
          { type: "drum", time: "3:3", drum: "hat", velocity: 0.38 },
          { type: "drum", time: "3:3:2", drum: "hat", velocity: 0.4 },
        ],
      },
    ],
  },
];

